version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
     - back
  api:
    image: 'ng6aspcore'
    expose:
      - "80"
    ports:
     - "5000:80"
    depends_on:
     - "db"
    networks:
     - back
  web:
    image: 'ng6'
    ports:
     - "80:80"
    depends_on:
     - "api"
    networks:
     - back
networks:
  back:
    driver: bridge