version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 123
  api:
    container_name: 'ng6aspcore'
    image: 'ng6aspcore'
    build:
      context: ./Api
      dockerfile: Api/Dockerfile
    ports:
     - "5000:80"
    depends_on:
     - "db"
  web:
    container_name: 'ng6'
    image: 'ng6'
    build:
      context: ./Client
      dockerfile: Client/Dockerfile
    ports:
     - "80:80"
    depends_on:
     - "api"